package geldautomat;
public enum GeldautomatZustand {
	
	AUF_KARTE_WARTEN,
	AUF_MENUEAUSWAHL_WARTEN,
	AUF_PIN_WARTEN,
	WIEDER_AUF_PIN_WARTEN,
	AUF_AKTION_WARTEN,
	AUF_BETRAG_WARTEN,
	AUF_BESTAETIGUNG_WARTEN;

}
